### PR TITLE
Optimize the Count kernel for less LDS usage to achieve full occupancy

### PR DESCRIPTION
**Pull request by KaoCC**
Optimize the Count kernel to let it use less LDS and could achieve full occupancy.

### CODE REVIEW

**Comment by KaoCC** [comment]
Before:
Capture_old_count

**Comment by KaoCC** [comment]
After optimization:
Capture_new_count

**Comment by KaoCC** [comment]
The runtime of the count kernel is also reduced.

**Comment by KaoCC** [comment]
Update to remove the boundary check in the loop. Now the upper bound is set only once before going into the loop.

**Review by takahiroharada — APPROVED** [review]
Nice. Count kernel is far faster now. This is what I got. 

```
executing on AMD Radeon RX 6900 XT (gfx1030), 40 SIMDs
compiling kernels ...
0.95ms (0.17GKeys/s) sorting 0.2Mkeys
0.88ms (0.18GKeys/s) sorting 0.2Mkeys
1.56ms (0.10GKeys/s) sorting 0.2Mkeys
0.85ms (0.19GKeys/s) sorting 0.2Mkeys
passed: 160.00K keys
1.30ms (1.23GKeys/s) sorting 1.6Mkeys
1.31ms (1.22GKeys/s) sorting 1.6Mkeys
1.30ms (1.23GKeys/s) sorting 1.6Mkeys
1.30ms (1.23GKeys/s) sorting 1.6Mkeys
passed: 1600.00K keys
5.12ms (3.13GKeys/s) sorting 16.0Mkeys
5.39ms (2.97GKeys/s) sorting 16.0Mkeys
5.34ms (3.00GKeys/s) sorting 16.0Mkeys
5.34ms (2.99GKeys/s) sorting 16.0Mkeys
passed: 16000.00K keys
>> done
```

**Pull request merged**
